#  image_id=13089493(Ubuntu 14.04 x64) 13090046(CentOS 6.7 x64) 10322623(CentOS 7 x64)
- name: Create droplet in DigitalOcean
  tags: droplet
  digital_ocean:
    state=present
    command=droplet
    id={{ did }}
    name=mydroplet-wordpress
    ssh_key_ids={{ ssh_id.ssh_key.id }}
    api_key={{ mytoken }}
    client_id={{ clientid }}
    image_id=10322623
    size_id=66
    region_id=6
    wait_timeout=500
  register: my_droplet
  run_once: true
- add_host: name={{ my_droplet.droplet.ip_address }} groupname=launched
- debug: msg="ID is {{ my_droplet.droplet.id }}"
- debug: msg="IP is {{ my_droplet.droplet.ip_address }}"

- name: Wait for SSH to come up
  wait_for: host={{ my_droplet.droplet.ip_address }} port=22 delay=10 timeout=320 state=started

