---
  # Ubuntu
  - name: Latest install Ansible
    apt: pkg=software-properties-common state=latest update_cache=yes
  - name: Add Reposotpry
    apt_repository: repo='ppa:ansible/ansible'
  - name: Install ansible
    apt: pkg=ansible state=latest update_cache=yes
